apiVersion: v1
kind: Namespace
metadata:
  name: shared-mysql
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: mysql
  name: mysql
  namespace: shared-mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - image: mysql:5.6
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: sysfraud
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
    name: mysql
    namespace: shared-mysql
    annotations:
      kubernetes.io/ssl-redirect: "false"
spec:
    rules:
    - host: mysql.frd.qa.bestday.net
      http:
        paths:
        - backend:
            serviceName: mysql
            servicePort: 3306
          path: /
---
apiVersion: v1
kind: Service
metadata:
    name: mysql
    namespace: shared-mysql
spec:
    ports:
    - name: http
      port: 3306
      targetPort: 3306
    selector:
        app: mysql